### PR TITLE
Add command to clear screen

### PR DESCRIPTION
**Pull request by hufuhufu**
Added simple command to clear the screen
I was going to name it clearScreen but cls is shorter and exactly same as windows cmd'
Also added help load and couple of minor fixes (forced by jshint)

### CODE REVIEW

**Comment by jettcrowson** [comment]
Hi sorry, this is not compatible with V0.3, should I put them in the new version or would you be willing to?

**Comment by hufuhufu** [comment]
Okay i've fixed the conflict
It should be mergeable now

**Comment by jettcrowson** [comment]
Sorry, already included your changes in the next version, but thanks

**Comment by hufuhufu** [comment]
Oh ok then
Closing

**Pull request closed without merging**
