### PR TITLE
Added the ability to sell data.

### PR DESCRIPTION
**Pull request by makiki99**
For now, I decided to use 1 data --> 1 money exchange value.
Money should be used to buy upgrades in my opinion. There also should be something to limit maximum ammount of data, because no PC can hold infinite ammount of data.

I also changed `<div id="dataCount">` into a `<span>` element, because it has `display:inline` value as default.

### CODE REVIEW

**Comment by ivanatora** [comment]
I like those!

Btw, should we use default byte, KB, MB, GB, etc units for `data`?

**Comment by makiki99** [comment]
Using bytes, kilobytes, etc. makes sense. Oh, and to clarify, I didn't implemented `maxData` or something like that - I just suggested that.

**Comment by ivanatora** [comment]
Putting a data cap would make the player buy some storage. It would be an interesting game component. Maybe even organize it in RAID 0/1, maybe even throw a few random events here and there - disk corruptions *wink* *wink*

**Comment by makiki99** [comment]
Disk corruptions wouldn't be fun in this type of game IMO. They would be either frustrating or negligible.

**Comment by jettcrowson** [comment]
Coming in next version

**Pull request closed without merging**
