### PR TITLE
Added todo item for myself

### PR DESCRIPTION
**Pull request by Crownie88**
Will post results on reddit developers sub.

### CODE REVIEW

**Comment by jettcrowson** [comment]
What are your plans for restructuring?

**Comment by Crownie88** [comment]
Seperating the CMD class from index.js is one step.  
Reading commands, storages, themes etc from json is the next.

Already started a bit.  
If you look at my fork I added a temporary branch there. Already commited a big bunch.
Still have to test it all but from what I saw it seemed to be working. 

Anyhow you can preview the changes a bit.
[CMD class](https://github.com/Crownie88/jettcrowson.github.io/blob/Temporary-branch/CMD%2B%2B/js/CMD_BaseClass.js is what we have now in index.js
[CMD manager class](https://github.com/Crownie88/jettcrowson.github.io/blob/Temporary-branch/CMD%2B%2B/js/CMD_Manager.js) Handles getting commands etc.

Added some css too and index2.js which is my own version of the new index.js

**Comment by jettcrowson** [comment]
This looks a lot better! Thanks

**Comment by Crownie88** [comment]
Well its still a work in progress. 
Might commit it tomorrow but will need loads of testing before it can go live imo.

**Comment by jettcrowson** [comment]
I can help test and whatnot

**Comment by jettcrowson** [comment]
I was looking through your code and wondering what is the point of the JSON
if you just restate all the variables?

**Pull request merged**
